### ISSUE TITLE
Ensure document chunks can be tied back to the original document

### ISSUE THREAD

**Issue by nassir90** [Antyk45/IBM-Chatbot#34]
At present the `source` metadata parameter on document chunks is just set to the name of the the source CSV file name. This is problematic as after vector search retrieves relevant document chunks, we want to be able to access the original document. You will need to figure out some way to uniquely identify each CSV row (review) and figure out a way of attaching metadata to the document chunks so that you can go from a document chunk → the original document. This task can be considered done if, after vector search, for any relevant document chunk, you are able to retrieve the original document.

**Comment by delladoh** [comment]
I added a method which adds a unique identifier (in form CSVFilename_rowNumber) to each row in the uploaded CSV File. This will allow use to like the chunks of the langchain docs back to original doc.
