### ISSUE TITLE
Review scraping for online shopping sites

### ISSUE THREAD

**Issue by dctcd** [Antyk45/IBM-Chatbot#76]

**Comment by nassir90** [comment]
Research was performed by @dymartin on this topic. It was concluded that review scraping is against the terms of service of the majority of ecommerce products so this feature will not be pursued.

**Comment by dctcd** [comment]
Research was performed by @dymartin on this topic. It was concluded that review scraping is against the terms of service of the majority of ecommerce products so this feature will not be pursued.
